services:

  backend:
    volumes:
      - ./backend/.:/app
      - ./backend/node_modules:/app/node_modules
      - ./migrations:/app/migrations
    ports:
      - "3000:3000"
    command: npm run start:debug

  frontend:
    volumes:
      - ./frontend/.:/app/
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "4000:4000"
