services:

  backend:
    volumes:
      - ./backend/.:/app
      - /app/node_modules
      - ./migrations:/app/migrations
    command: npm run start:debug

  frontend:
    volumes:
      - ./frontend/.:/app/
      - /app/node_modules
