version: "3.8"
services:

  backend:
    volumes:
      - ./backend/.:/app
      - ./backend/node_modules:/app/node_modules
      - ./backend/migrations:/app/migrations

    command: npm run start:debug

  frontend:
    volumes:
      - ./frontend/.:/app/
      - ./frontend/node_modules:/app/node_modules
