services:
  external-app-backend:
    build:
      context: ./stripe-validation-app/backend/.
      dockerfile: Dockerfile
    environment:
      STRIPE_SECRET_KEY: #sk_xxxxxxxxxxxxxxxxx find this into stripe dashboard
      STRIPE_PRODUCT_PRICE_ID: #price_xxxxxxxxxx find this into stripe dashboard
      OIDC_CLIENT_ID: #client id from open id
      OIDC_CLIENT_SECRET: #client secret from open id
      OIDC_REDIRECT_URI: #redirect uri authorized by open id issuer same as frontend one
      OIDC_ISSUER: #url for oidc issuer
      PASSPORT_SESSION_SECRET: #random session secret at least 14 characters
    restart: always
    networks:
      - stripe_validation_network

  external-app-frontend:
    build:
      context: ./stripe-validation-app/frontend/.
      dockerfile: Dockerfile
      args:
        VITE_OIDC_REDIRECT_URI: #redirect uri authorized by open id issuer same as backend one
        VITE_BACKEND_URL: #https://mmu-backend.your-domain.com
        VITE_OIDC_ISSUER: #url for oidc issuer
        VITE_OIDC_CLIENT_ID: #client id from open id
        VITE_MMU_OIDC_CONNECT_URL: #MMU url for process oidc login https://your.mmu.url/auth/openId-callback
    environment:
      VITE_MMU_URL: #https://your.mmu.url/
      VITE_OIDC_REDIRECT_URI: #redirect uri authorized by open id issuer same as backend one
      VITE_MMU_OIDC_CONNECT_URL:  #MMU url for process oidc login https://your.mmu.url/auth/openId-callback
      VITE_OIDC_ISSUER: #url for oidc issuer
      VITE_OIDC_CLIENT_ID: #client id from open id
      VITE_BACKEND_URL: #https://mmu-backend.your-domain.com
    restart: always
    networks:
      - stripe_validation_network

networks:
  stripe_validation_network:
    driver: bridge