services:
  external-app-backend:
    build:
      context: ./stripe-validation-app/backend/.
      dockerfile: Dockerfile
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PRODUCT_PRICE_ID: ${STRIPE_PRODUCT_PRICE_ID}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_REDIRECT_URI: ${OIDC_REDIRECT_URI}
      OIDC_ISSUER: ${OIDC_ISSUER}
      PASSPORT_SESSION_SECRET: ${PASSPORT_SESSION_SECRET}
    restart: always
    ports:
      - "3000"
    networks:
      - stripe_validation_network

  external-app-frontend:
    build:
      context: ./stripe-validation-app/frontend/.
      dockerfile: Dockerfile
      args:
        VITE_OIDC_REDIRECT_URI: ${VITE_OIDC_REDIRECT_URI}
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_OIDC_ISSUER: ${VITE_OIDC_ISSUER}
        VITE_OIDC_CLIENT_ID: ${VITE_OIDC_CLIENT_ID}
        VITE_MMU_OIDC_CONNECT_URL: ${VITE_MMU_OIDC_CONNECT_URL}
    environment:
      VITE_MMU_URL: ${VITE_MMU_URL}
      VITE_OIDC_REDIRECT_URI: ${VITE_OIDC_REDIRECT_URI}
      VITE_MMU_OIDC_CONNECT_URL: ${VITE_MMU_OIDC_CONNECT_URL}
      VITE_OIDC_ISSUER: ${VITE_OIDC_ISSUER}
      VITE_OIDC_CLIENT_ID: ${VITE_OIDC_CLIENT_ID}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    restart: always
    ports:
      - "4000"
    networks:
      - stripe_validation_network

networks:
  stripe_validation_network:
    driver: bridge