name: Generate Changelog

on:
  push:
    tags:
      - 'v*'  # trigger on new version tags

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install git-cliff
        run: |
          curl -sSL https://github.com/orhun/git-cliff/archive/refs/tags/v2.8.0.tar.gz | tar -xz
          sudo mv git-cliff-2.8.0 /usr/local/bin/

      - name: Generate changelog
        run: git-cliff -o CHANGELOG.md

      - name: Commit changelog
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog for ${{ github.ref_name }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

